apiVersion: apps/v1
kind: Deployment
metadata:
  name: addresses-server
  labels:
    app: addresses-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addresses-server
  template:
    metadata:
      labels:
        app: addresses-server
    spec:
      containers:
        - name: addresses-server
          image: sebacassone/addresses-server:latest # Cambia a tu imagen publicada en Docker Hub
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "addresses_db" # Cambia este valor según la base de datos requerida
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER # Cambia este valor según tu configuración
