apiVersion: apps/v1
kind: Deployment
metadata:
  name: debts-server
  labels:
    app: debts-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debts-server
  template:
    metadata:
      labels:
        app: debts-server
    spec:
      containers:
        - name: debts-server
          image: sebacassone/debts-server:latest # Cambia a tu imagen publicada en Docker Hub
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "debts_db"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
