apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-server
  labels:
    app: documents-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents-server
  template:
    metadata:
      labels:
        app: documents-server
    spec:
      containers:
        - name: documents-server
          image: sebacassone/documents-server:latest # Cambia a tu imagen publicada en Docker Hub
          env:
            - name: DB_HOST
              value: "documents-db-service.default.svc.cluster.local:5432"
            - name: DB_NAME
              value: "documents_db"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
