apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server-deployment
  labels:
    app: frontend-server-deployment
spec:
  selector:
    matchLabels:
      app: frontend-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-server-deployment
    spec:
      containers:
        - name: frontend-server-container
          image: sebacassone/frontend-server:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-server-service
  labels:
    app: frontend-server
spec:
  selector:
    app: frontend-server-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  type: LoadBalancer
