apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-server-deployment
  labels:
    app: prueba-server-deployment
spec:
  selector:
    matchLabels:
      app: prueba-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: prueba-server-deployment
    spec:
      containers:
        - name: prueba-server
          image: sebacassone/prueba-server:latest
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
