apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-server
  labels:
    app: users-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-server
  template:
    metadata:
      labels:
        app: users-server
    spec:
      containers:
        - name: users-server
          image: sebacassone/users-server:latest # Cambia a tu imagen publicada en Docker Hub
          env:
            - name: DB_HOST
              value: "users-db-service.default.svc.cluster.local:5432"
            - name: DB_NAME
              value: "postgres" # Cambia este valor según la base de datos requerida
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
