server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations: {}
      routes:
        - id: jenkins-service
          uri: http://jenkins-service:9000
          predicates:
            - Path=/jenkins/** # Rutas que empiezan con /jenkins/
        - id: prueba-server
          uri: lb://prueba-server
          predicates:
            - Path=/prueba/**
          filters:
            - StripPrefix=1
        - id: address-server
          uri: lb://address-server
          predicates:
            - Path=/api/v1/address/**
        - id: debts-server
          uri: lb://debts-server
          predicates:
            - Path=/api/v1/debts/**
        - id: debts-user-server
          uri: lb://debts-server
          predicates:
              - Path=/api/v1/debts/user/**
        - id: documents-server
          uri: lb://documents-server
          predicates:
            - Path=/api/v1/documents/**
        - id: loans-server
          uri: lb://loans-server
          predicates:
              - Path=/api/v1/loans/**
        - id: users-server
          uri: lb://users-server
          predicates:
            - Path=/api/v1/user/**
        - id: users-incomes-server
          uri: lb://users-server
          predicates:
              - Path=/api/v1/incomes/**
        - id: users-jobs-server
          uri: lb://users-server
          predicates:
              - Path=/api/v1/jobs/**
        - id: loans-server
          uri: lb://loans-server
          predicates:
              - Path=/api/v1/loans/**
        - id: loans-evaluations-server
          uri: lb://loans-server
          predicates:
              - Path=/api/v1/evaluations/**
        - id: loans-requests-server
          uri: lb://loans-server
          predicates:
              - Path=/api/v1/requests/**
