server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Laboratorio-de-Informatica-Usach/microservices-patterns
          username: adminDiinfUsach2024
          password: ${GITHUB_TOKEN}
          search-paths: config-data
  application:
    name: config-server
